Feature/create an account
patrykmierunski/budgetr pull request #1
Opened 2023-01-17 12:23 UTC by mantiscrab

Main success flow:
1. User fulfills information needed to create an account, namely: email, username and password.
3. System registers this information and hashes password
2. System informs user that account has been created and provide information about username and email address

Alternate flow 1:
1. If user with a specified email address exists, the website informs about it.

Alternate flow 2:
1. If user with a specified username exists, the website informs about it.

2023-01-17 13:10 UTC, greencashew commented
In context of bigger projects, it is worth to squash commits into one, after review :-) 

In here i've got the idea, you wanted to show me steps of implementation

2023-01-19 07:24 UTC, greencashew commented
Missing tests, consider to write integration tests, which verify behaviour but doesn't check logic

2023-01-19 07:44 UTC, greencashew requested changes

2023-01-19 07:44 UTC, greencashew commented on pom.xml
> -	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
MINOR: I know it's project generated by spring.io, so you change formatting to your own. In case you join the team you need to ask for code formatting settings.

Cause for now it's hard to detmine for me what you changed :-)

2023-01-19 07:44 UTC, greencashew commented on pom.xml
> +        <dependency>
MINOR: Just from readablity perspective, you can add comment in here to separate dev environment dependencies

2023-01-19 07:44 UTC, greencashew commented on src/main/java/pl/mantiscrab/budgetr/config/SecurityConfig.java
> +//        http.csrf(csrf -> csrf.ignoringRequestMatchers(PathRequest.toH2Console()));
Remove redundant comment

2023-01-19 07:44 UTC, greencashew commented on src/main/java/pl/mantiscrab/budgetr/config/SecurityConfig.java
> +        UserDetails admin = User.builder().username("admin").password(password).roles("admin").build();
Please explain why? And what is the further plan?

2023-01-19 07:44 UTC, greencashew commented on src/main/resources/application.yml
> +    password: password
Just keep in mind, that in normal environment it should be passed by ENVIRONMENT_VARIABLE

As far as I Remember it's redundant in here

2023-01-19 07:44 UTC, greencashew commented on src/main/java/pl/mantiscrab/budgetr/registration/User.java
> +    @Column(nullable = false, unique = true)
MINOR: \n between fields, it will be more readable

2023-01-19 07:44 UTC, greencashew commented on src/main/java/pl/mantiscrab/budgetr/registration/User.java
> +    @NotBlank
Question do you really need validation in here, if you do exactly same on dto level

2023-01-19 07:44 UTC, greencashew commented on src/main/java/pl/mantiscrab/budgetr/registration/UserMapper.java
> +class UserMapper {
Personally, i prefer, to make object responsible for its creation and business logic. But this is also fine, and in some cases even better ;-) 

Btw. for mapping you can also try `mapstruct` library if you wish

2023-01-19 07:44 UTC, greencashew commented on src/main/java/pl/mantiscrab/budgetr/registration/UserService.java
> +    @Transactional
Do you need transaction in here? :-)

2023-01-19 07:44 UTC, greencashew commented on src/main/java/pl/mantiscrab/budgetr/registration/UserRegistrationDto.java
> +record UserRegistrationDto(String email, String username, String password) {
For now i don't see any value with this Dto, In service layer you can operate on entity, don't be shy it's your internal

2023-01-19 07:44 UTC, greencashew commented on src/main/java/pl/mantiscrab/budgetr/registration/UserController.java
> +    List<ConstraintViolation> handleMethodArgumentNotValidException(MethodArgumentNotValidException ex) {
Good that you remembered about it :-) 

If you wish to see how I implemented that generic exception you can follow the page:
https://github.com/greencashew/spring-link-shortener/tree/main/src/main/java/dev/greencashew/link_shortener/configuration/web/exception_handling

2023-01-19 07:44 UTC, greencashew commented on src/main/java/pl/mantiscrab/budgetr/registration/UserService.java
> +    private void throwIfUserExist(UserRegisterDto dto) {
Please clearly state name, what is the purpose

2023-01-19 15:54 UTC, mantiscrab commented on src/main/java/pl/mantiscrab/budgetr/config/SecurityConfig.java
> +        UserDetails admin = User.builder().username("admin").password(password).roles("admin").build();
Signing in will be added in next PR

2023-01-19 15:54 UTC, mantiscrab commented on src/main/java/pl/mantiscrab/budgetr/registration/UserMapper.java
> +class UserMapper {
I plan to add `mapstruct` later

2023-01-19 15:56 UTC, mantiscrab commented
> Missing tests, consider to write integration tests, which verify behaviour but doesn't check logic

For now there's no business logic, just infrastructure. I will add integration test with business logic.

2023-01-19 16:06 UTC, greencashew commented
> > Missing tests, consider to write integration tests, which verify behaviour but doesn't check logic
> 
> For now there's no business logic, just infrastructure. I will add integration test with business logic.

I do not agree,  it is kind of business logic but in different domain

2023-01-19 16:23 UTC, greencashew commented on src/main/java/pl/mantiscrab/budgetr/registration/User.java
> +    @Column(nullable = false, unique = true)
Still not added

2023-01-19 19:01 UTC, greencashew approved these changes
After discussion I'm Ok too go. Waiting for the further improvements

2023-01-24 12:28 UTC, greencashew commented on src/test/java/pl/mantiscrab/budgetr/registration/RegistrationTest.java
> +    void registrationTest() {
The test method could be description

E.g.
shouldRegisterUserWhenNotExists

Or with description

2023-01-24 12:28 UTC, greencashew commented on src/test/java/pl/mantiscrab/budgetr/registration/RegistrationTest.java
> +    private void assertRegisterResponseMatchesRequest(UserDto registrationResponse, UserRegisterDto registerRequest) {
Please keep in mind that tests instead of clean should be mainly simple, and duplicates are fully fine.

For me you extracted to too many methods in this case

2023-01-24 12:28 UTC, greencashew commented on src/test/java/pl/mantiscrab/budgetr/registration/RegistrationTest.java
> +class RegistrationTest {
I remember it was some way to make it functional but don't remember so far

2023-01-24 12:28 UTC, greencashew commented on src/test/java/pl/mantiscrab/budgetr/registration/InMemoryDummyCrudRepository.java
> +        return null;
Better to throw exception if it is not implemented

2023-01-24 12:28 UTC, greencashew commented on src/test/java/pl/mantiscrab/budgetr/registration/InMemoryDummyCrudRepository.java
> +class InMemoryDummyCrudRepository<T, ID> implements CrudRepository<T, ID> {
This may cause parallisation issues as you implemented in synchronous way

2023-01-24 12:28 UTC, greencashew commented on src/test/java/pl/mantiscrab/budgetr/registration/InMemoryUserRepository.java
> +        return new User(index++, user.getEmail(), user.getUsername(), user.getPassword());
Interesting idea, I was using username as primary key 🙂

2023-01-24 12:57 UTC, mantiscrab commented on src/test/java/pl/mantiscrab/budgetr/registration/InMemoryDummyCrudRepository.java
> +class InMemoryDummyCrudRepository<T, ID> implements CrudRepository<T, ID> {
I'm not planning to run unit tests synchronously, so I assume that this one i fine

2023-01-24 13:51 UTC, greencashew commented on src/test/java/pl/mantiscrab/budgetr/registration/InMemoryDummyCrudRepository.java
> +class InMemoryDummyCrudRepository<T, ID> implements CrudRepository<T, ID> {
sure just wanted to point it out

2023-01-24 13:55 UTC, greencashew approved these changes

2023-01-24 13:55 UTC, greencashew commented on src/test/java/pl/mantiscrab/budgetr/registration/MethodNotImplementedException.java
> +class MethodNotImplementedException extends RuntimeException{
You don't have to create new Exception for that, there is already one in place

2023-01-24 14:05 UTC, merged